project_name: "VDown Video"
default_status: "To Do"
statuses: ["To Do", "In Progress", "Done"]
labels: []
definition_of_done: ["Unit test are present and covers > 70%", "E2e Tests are present and covers > 70%"]
date_format: yyyy-mm-dd
max_column_width: 20
default_editor: "nano"
auto_open_browser: true
default_port: 6420
remote_operations: true
auto_commit: false
filesystem_only: false
bypass_git_hooks: false
check_active_branches: true
active_branch_days: 30
task_prefix: "task"
